--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2026. 04. 13. 9:18:29
-- Server version: 5.7.44
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS doomshop;

CREATE DATABASE IF NOT EXISTS doomshop
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE doomshop;

--
-- Create table `albums`
--
CREATE TABLE IF NOT EXISTS albums (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(191) NOT NULL,
  cover VARCHAR(191) DEFAULT NULL,
  release_date DATE DEFAULT NULL,
  price_eur DECIMAL(8, 2) NOT NULL DEFAULT 0.00,
  description TEXT DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `albums_title_unique` on table `albums`
--
ALTER TABLE albums 
  ADD UNIQUE INDEX albums_title_unique(title);

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL,
  password VARCHAR(191) NOT NULL,
  role INT(11) NOT NULL DEFAULT 2,
  phone VARCHAR(191) DEFAULT NULL,
  city VARCHAR(191) DEFAULT NULL,
  street VARCHAR(191) DEFAULT NULL,
  house_number VARCHAR(191) DEFAULT NULL,
  zip_code VARCHAR(191) DEFAULT NULL,
  billing_phone VARCHAR(191) DEFAULT NULL,
  billing_city VARCHAR(191) DEFAULT NULL,
  billing_street VARCHAR(191) DEFAULT NULL,
  billing_house_number VARCHAR(191) DEFAULT NULL,
  billing_zip_code VARCHAR(191) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `users_email_unique` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX users_email_unique(email);

--
-- Create table `carts`
--
CREATE TABLE IF NOT EXISTS carts (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT(20) UNSIGNED NOT NULL,
  date DATE NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE carts 
  ADD CONSTRAINT carts_user_id_foreign FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE;

--
-- Create table `genres`
--
CREATE TABLE IF NOT EXISTS genres (
  genre_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  genre_name VARCHAR(191) NOT NULL,
  PRIMARY KEY (genre_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 16,
AVG_ROW_LENGTH = 1092,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `genres_genre_name_unique` on table `genres`
--
ALTER TABLE genres 
  ADD UNIQUE INDEX genres_genre_name_unique(genre_name);

--
-- Create table `tracks`
--
CREATE TABLE IF NOT EXISTS tracks (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  genre_id BIGINT(20) UNSIGNED NOT NULL,
  album_id BIGINT(20) UNSIGNED DEFAULT NULL,
  track_title VARCHAR(191) NOT NULL,
  bpm_value INT(11) DEFAULT NULL,
  release_date DATE DEFAULT NULL,
  track_length_sec INT(11) DEFAULT NULL,
  track_price_eur DECIMAL(8, 2) NOT NULL DEFAULT 1.99,
  track_cover VARCHAR(191) DEFAULT NULL,
  track_path VARCHAR(191) DEFAULT NULL,
  preview_start_at INT(11) NOT NULL DEFAULT 0,
  preview_end_at INT(11) NOT NULL DEFAULT 30,
  preview_path VARCHAR(191) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 84,
AVG_ROW_LENGTH = 606,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `tracks_track_title_unique` on table `tracks`
--
ALTER TABLE tracks 
  ADD UNIQUE INDEX tracks_track_title_unique(track_title);

--
-- Create foreign key
--
ALTER TABLE tracks 
  ADD CONSTRAINT tracks_album_id_foreign FOREIGN KEY (album_id)
    REFERENCES albums(id) ON DELETE SET NULL;

--
-- Create foreign key
--
ALTER TABLE tracks 
  ADD CONSTRAINT tracks_genre_id_foreign FOREIGN KEY (genre_id)
    REFERENCES genres(genre_id) ON DELETE CASCADE;

--
-- Create table `track_genres`
--
CREATE TABLE IF NOT EXISTS track_genres (
  track_id BIGINT(20) UNSIGNED NOT NULL,
  genre_id BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (track_id, genre_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE track_genres 
  ADD CONSTRAINT track_genres_genre_id_foreign FOREIGN KEY (genre_id)
    REFERENCES genres(genre_id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE track_genres 
  ADD CONSTRAINT track_genres_track_id_foreign FOREIGN KEY (track_id)
    REFERENCES tracks(id) ON DELETE CASCADE;

--
-- Create table `cart_items`
--
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  cart_id BIGINT(20) UNSIGNED NOT NULL,
  track_id BIGINT(20) UNSIGNED DEFAULT NULL,
  album_id BIGINT(20) UNSIGNED DEFAULT NULL,
  pcs INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE cart_items 
  ADD CONSTRAINT cart_items_album_id_foreign FOREIGN KEY (album_id)
    REFERENCES albums(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE cart_items 
  ADD CONSTRAINT cart_items_cart_id_foreign FOREIGN KEY (cart_id)
    REFERENCES carts(id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE cart_items 
  ADD CONSTRAINT cart_items_track_id_foreign FOREIGN KEY (track_id)
    REFERENCES tracks(id) ON DELETE CASCADE;

--
-- Create table `artists`
--
CREATE TABLE IF NOT EXISTS artists (
  artist_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  artist_name VARCHAR(191) NOT NULL,
  artist_picture VARCHAR(191) DEFAULT NULL,
  PRIMARY KEY (artist_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 46,
AVG_ROW_LENGTH = 364,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `artists_artist_name_unique` on table `artists`
--
ALTER TABLE artists 
  ADD UNIQUE INDEX artists_artist_name_unique(artist_name);

--
-- Create table `track_artists`
--
CREATE TABLE IF NOT EXISTS track_artists (
  track_id BIGINT(20) UNSIGNED NOT NULL,
  artist_id BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (track_id, artist_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 202,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE track_artists 
  ADD CONSTRAINT track_artists_artist_id_foreign FOREIGN KEY (artist_id)
    REFERENCES artists(artist_id) ON DELETE CASCADE;

--
-- Create foreign key
--
ALTER TABLE track_artists 
  ADD CONSTRAINT track_artists_track_id_foreign FOREIGN KEY (track_id)
    REFERENCES tracks(id) ON DELETE CASCADE;

--
-- Create table `sessions`
--
CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(191) NOT NULL,
  user_id BIGINT(20) UNSIGNED DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  payload LONGTEXT NOT NULL,
  last_activity INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `sessions_last_activity_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_last_activity_index(last_activity);

--
-- Create index `sessions_user_id_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_user_id_index(user_id);

--
-- Create table `recommendation_links`
--
CREATE TABLE IF NOT EXISTS recommendation_links (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  media_url VARCHAR(2048) NOT NULL,
  sort_order TINYINT(4) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `personal_access_tokens`
--
CREATE TABLE IF NOT EXISTS personal_access_tokens (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  tokenable_type VARCHAR(191) NOT NULL,
  tokenable_id BIGINT(20) UNSIGNED NOT NULL,
  name TEXT NOT NULL,
  token VARCHAR(64) NOT NULL,
  abilities TEXT DEFAULT NULL,
  last_used_at TIMESTAMP NULL DEFAULT NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 28,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `personal_access_tokens_expires_at_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_expires_at_index(expires_at);

--
-- Create index `personal_access_tokens_token_unique` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD UNIQUE INDEX personal_access_tokens_token_unique(token);

--
-- Create index `personal_access_tokens_tokenable_type_tokenable_id_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_tokenable_type_tokenable_id_index(tokenable_type, tokenable_id);

--
-- Create table `password_reset_tokens`
--
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  email VARCHAR(191) NOT NULL,
  token VARCHAR(191) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (email)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `migrations`
--
CREATE TABLE IF NOT EXISTS migrations (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  migration VARCHAR(191) NOT NULL,
  batch INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 64,
AVG_ROW_LENGTH = 780,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `liveshow_links`
--
CREATE TABLE IF NOT EXISTS liveshow_links (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  youtube_url VARCHAR(2048) NOT NULL,
  sort_order TINYINT(4) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `job_batches`
--
CREATE TABLE IF NOT EXISTS job_batches (
  id VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  total_jobs INT(11) NOT NULL,
  pending_jobs INT(11) NOT NULL,
  failed_jobs INT(11) NOT NULL,
  failed_job_ids LONGTEXT NOT NULL,
  options MEDIUMTEXT DEFAULT NULL,
  cancelled_at INT(11) DEFAULT NULL,
  created_at INT(11) NOT NULL,
  finished_at INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `jobs`
--
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  queue VARCHAR(191) NOT NULL,
  payload LONGTEXT NOT NULL,
  attempts TINYINT(3) UNSIGNED NOT NULL,
  reserved_at INT(10) UNSIGNED DEFAULT NULL,
  available_at INT(10) UNSIGNED NOT NULL,
  created_at INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `jobs_queue_index` on table `jobs`
--
ALTER TABLE jobs 
  ADD INDEX jobs_queue_index(queue);

--
-- Create table `failed_jobs`
--
CREATE TABLE IF NOT EXISTS failed_jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(191) NOT NULL,
  `connection` TEXT NOT NULL,
  queue TEXT NOT NULL,
  payload LONGTEXT NOT NULL,
  exception LONGTEXT NOT NULL,
  failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `failed_jobs_uuid_unique` on table `failed_jobs`
--
ALTER TABLE failed_jobs 
  ADD UNIQUE INDEX failed_jobs_uuid_unique(uuid);

--
-- Create table `cache_locks`
--
CREATE TABLE IF NOT EXISTS cache_locks (
  `key` VARCHAR(191) NOT NULL,
  owner VARCHAR(191) NOT NULL,
  expiration INT(11) NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `cache`
--
CREATE TABLE IF NOT EXISTS cache (
  `key` VARCHAR(191) NOT NULL,
  value MEDIUMTEXT NOT NULL,
  expiration INT(11) NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

-- 
-- Dumping data for table albums
--
INSERT INTO albums VALUES
(1, 'Beyond The Horizon', NULL, NULL, 0.00, NULL, 1),
(2, 'USB002 REMIXES', NULL, NULL, 0.00, NULL, 1),
(3, 'House', NULL, NULL, 0.00, NULL, 1);

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'Admin User', 'admin@doomshoprecords.com', '$2y$12$rmOeHRhs7RnP2fhO5sdFreKggVI6XO0to.DVlXtTim2FCqSqQ0Y22', 1, '+1-555-0100', 'Los Angeles', 'Sunset Blvd', '100', '90001', '+1-555-0100', 'Los Angeles', 'Sunset Blvd', '100', '90001'),
(2, 'Customer User', 'customer@doomshoprecords.com', '$2y$12$CpfBNpJlMZ28qsaPY/UrA.CptOSxiklLt/dffCC96t/jEV6AbE2ma', 2, '+1-555-0101', 'New York', 'Broadway', '200', '10001', '+1-555-0101', 'New York', 'Broadway', '200', '10001'),
(3, 'Molnár Kristóf', 'csangcsungcsing@gmail.com', '$2y$12$Omj5ofrzbtvBKs6Z14sIvupzwoieEt3cZFAVxT70BCO2HEzJHG8Xu', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table genres
--
INSERT INTO genres VALUES
(15, 'Dubstep'),
(12, 'Eletronic'),
(4, 'Hardcore'),
(1, 'Hardstyle'),
(8, 'Hip Hop/Rap'),
(10, 'Hip-Hop'),
(11, 'Hip-hop/Rap'),
(7, 'House'),
(5, 'Psytrance'),
(6, 'Rap'),
(3, 'Rawstyle'),
(2, 'Riddim'),
(13, 'Techno'),
(9, 'Turkish Hip Hop'),
(14, 'Uptempo');

-- 
-- Dumping data for table artists
--
INSERT INTO artists VALUES
(1, 'Subtronics', 'subtronics.png'),
(2, 'Krowdexx', 'krowdexx.png'),
(3, 'Rooler', 'rooler.png'),
(4, 'Sickmode', 'sickmode.png'),
(5, 'Mish', 'mish.png'),
(6, 'RiotShift', 'riotshift.png'),
(7, 'DEHA INC.', 'deha_inc.png'),
(8, 'Skazi', 'skazi.png'),
(9, 'Notype', 'notype.png'),
(10, 'TOZA', 'toza.jpg'),
(11, 'the floor', NULL),
(12, 'OK OK', NULL),
(13, 'Şehinşah', NULL),
(14, 'Fred again..', 'artists/qV4EkCy1BFspD1TZHL6tvgPnzGf8VLS35n9sB04I.jpg'),
(15, 'Mc Livid', NULL),
(16, 'Paul Elstak', NULL),
(17, 'SWIRF', 'artists/08PssPsf9vekHGbPjaWp1Yf4PpwH5eIdU1MgOm5v.jpg'),
(18, '13Killoki', 'artists/dsrNTtufCb8i4rvP0FPG6oS1N54Nqj2RzZnofLGA.jpg'),
(19, 'Tape B', NULL),
(20, 'Timmy Trumpet', NULL),
(21, 'GPF', 'artists/cMRq9xp02eOa0RGn5rRpF4OtOu6T3hOSm5oxT68i.jpg'),
(22, 'Dikke Baap', 'artists/E7Sih240F4tvTwZjSTLq543NkBq99e3g5Aqn4dRo.jpg'),
(23, 'Kenai', NULL),
(24, 'Warface', 'artists/DhLZyo0D9drx44zVgAdYO6RUdV7VyNNoW71BXFm5.webp'),
(25, 'MC Shocker', NULL),
(26, 'Levenkhan', 'artists/6rQG8Vv8IM1X8ktPjQ4FzU3ZHgML3FtPZgupB8yE.jpg'),
(27, 'Dr Donk', 'artists/krCcZlafHw9VvXoY6IUftQN1yjN1qiUyoVaX8dBx.jpg'),
(28, 'The Straikerz', 'artists/xLCAdJulFyIezc1KlB8rfFFLkosMgFWhDd8L1OJE.jpg'),
(29, 'Bloodlust', NULL),
(30, 'Carola', NULL),
(31, 'DJ Isaac', NULL),
(32, 'Rebelion', NULL),
(33, 'Micah Martin', NULL),
(34, 'Vertile', NULL),
(35, 'Villain', NULL),
(36, 'Dual Damage', NULL),
(37, 'Anderex', 'artists/aJntHgRKAPiccuYdF67kNsku5CvU4Hg0PbBedL2e.jpg'),
(38, 'Imperatorz', NULL),
(39, 'Facilita', NULL),
(40, 'Excision', NULL),
(41, 'Amidy', NULL),
(42, 'Dj Bountyhunter', NULL),
(43, 'Explorers of the Internet', NULL),
(44, 'Cyclops', NULL),
(45, 'Rezz', NULL);

-- 
-- Dumping data for table tracks
--
INSERT INTO tracks VALUES
(1, 2, NULL, 'Subtronics - Bubble Flex', 140, '2026-03-05', 210, 1.99, 'bubbleflex.jpg', 'tracks/[SubCarbon Records] Subtronics - Bubble Flex.mp3', 23, 53, 'previews/preview_1_c396de30-f14a-40c9-9304-71abeb91e957.mp3'),
(2, 1, NULL, 'Krowdexx & Mish - FEELIN'' HIGH (Extended Mix)', 160, '2026-03-05', 240, 1.99, 'feelinhigh.jpg', 'tracks/1. Krowdexx & Mish - FEELIN'' HIGH (Extended Mix).mp3', 48, 78, 'previews/preview_2_b8f102bc-ab18-4e02-8f90-2cdce17fcb1f.mp3'),
(3, 1, NULL, 'Krowdexx & TOZA - HARDSTYLE IS BACK (Original Mix)', 160, '2026-03-05', 210, 1.99, 'hardstyleisback.jpg', 'tracks/1. Krowdexx & TOZA - HARDSTYLE IS BACK (Original Mix).mp3', 58, 88, 'previews/preview_3_0ab9b114-62fa-43d5-9a7e-1e0b7360bf56.mp3'),
(4, 2, NULL, 'Excision & Subtronics - A.F.B.1.', 140, '2026-03-05', 210, 1.99, 'afb1.jpg', 'tracks/Excision &amp; Subtronics - A.F.B.1. .mp3', 154, 184, 'previews/preview_4_852f46f6-40af-4e18-9545-43c1b53cb61f.mp3'),
(5, 1, NULL, 'Krowdexx - All You Freaks (Extended Mix)', 160, '2026-03-05', 240, 1.99, 'allyourfreaks.jpg', 'tracks/Krowdexx - All You Freaks (Extended Mix).mp3', 47, 77, 'previews/preview_5_f3889d2b-c6b5-4d4b-bd7b-1313ccae87e8.mp3'),
(6, 1, NULL, 'Krowdexx - Bassfire (Extended Mix) ', 160, '2026-03-05', 240, 1.99, 'krowdexx-bassfire.jpg', 'tracks/Krowdexx - Bassfire (Extended Mix) .mp3', 67, 97, 'previews/preview_6_0cbfdcaf-c33f-47be-baa3-576760781c07.mp3'),
(7, 1, NULL, 'Krowdexx - How You Feel It (Extended Mix)', 160, '2026-03-05', 240, 1.99, 'howyoufeelit.jpg', 'tracks/Krowdexx - How You Feel It (Extended Mix).mp3', 54, 84, 'previews/preview_7_f71bce5c-86d9-479c-be29-e653a3712cc5.mp3'),
(8, 1, NULL, 'Krowdexx - KEROSENE (Extended Mix)', 160, '2026-03-05', 240, 1.99, 'kerosene.jpg', 'tracks/Krowdexx - KEROSENE (Extended Mix).mp3', 55, 85, 'previews/preview_8_2c7c145f-a522-4712-ae1d-f723433b2e2e.mp3'),
(9, 1, NULL, 'Krowdexx - So Hot (Extended Mix)', 160, '2026-03-05', 240, 1.99, 'sohot.jpg', 'tracks/Krowdexx - So Hot (Extended Mix).mp3', 150, 180, 'previews/preview_9_0bb55ce6-d3bb-4cfb-b8be-f79a8887323f.mp3'),
(10, 1, NULL, 'Krowdexx &amp; Holy Priest - Bass Powah (Extended Mix) ', 160, '2026-03-05', 240, 1.99, 'basspowah.jpg', 'tracks/Krowdexx &amp; Holy Priest - Bass Powah (Extended Mix) .mp3', 145, 175, 'previews/preview_10_fb517722-f42e-493b-9801-8c30ce8008d1.mp3'),
(11, 1, NULL, 'Krowdexx ft. Carola & Nolz - Nocturnal Rebellion (Rustyland Anthem 2024) (Extended Mix)', 160, '2026-03-05', 240, 1.99, 'noctrualrebellion.jpg', 'tracks/Krowdexx ft. Carola & Nolz - Nocturnal Rebellion (Rustyland Anthem 2024) (Extended Mix).mp3', 83, 113, 'previews/preview_11_9400a0e2-0932-47dd-a4c5-9cf472d1cf3e.mp3'),
(12, 1, NULL, 'Mish & Krowdexx - Time To Shine (Extended Mix)', 160, '2026-03-05', 240, 1.99, 'timetoshine.jpg', 'tracks/Mish & Krowdexx - Time To Shine (Extended Mix).mp3', 0, 30, 'previews/preview_12_b0fbe517-c030-4b64-a412-8188e9f35762.mp3'),
(13, 1, NULL, 'Mish & Krowdexx feat. MC Livid - ETERNAL PULSE (Shutdown Festival 2025 Anthem) (Extended Mix)', 160, '2026-03-05', 240, 1.99, 'ethernalpulse.jpg', 'tracks/Mish &amp; Krowdexx feat. MC Livid - ETERNAL PULSE (Shutdown Festival 2025 Anthem) (Extended Mix) .mp3', 35, 65, 'previews/preview_13_3cc97fa2-4a5c-484a-9158-a4fe406a97e4.mp3'),
(14, 1, NULL, 'Mish - RAVE IN PARADISE (Extented Mix)', 160, '2026-03-05', 240, 1.99, 'raveinparadise.jpg', 'tracks/Mish_-_rave_in_paradise_(official_free_festival_2023_anthem)_(extended_mix).mp3', 41, 71, 'previews/preview_14_ceb8b005-a57b-49a4-8a93-03251bd647e0.mp3'),
(15, 2, NULL, 'Rezz, Subtronics - Puzzle Box', 140, '2026-03-05', 210, 1.99, 'puzzlebox.jpg', 'tracks/Rezz, Subtronics - Puzzle Box .mp3', 70, 100, 'previews/preview_15_9ff428e6-cdb1-473a-bdc7-65e723bfcf68.mp3'),
(16, 3, NULL, 'Rooler - FEEL DA RHYTHM (Extended Mix)', 155, '2026-03-05', 240, 1.99, 'feeldarythm.jpg', 'tracks/Rooler - FEEL DA RHYTHM (Extended Mix).mp3', 86, 116, 'previews/preview_16_0136ec36-88fb-485a-91c4-ad1b4788ed99.mp3'),
(17, 3, NULL, 'Rooler & Atmozfears - INTO THE WILD (Official Intents Festival 2024 Anthem) (Extended Mix)', 155, '2026-03-05', 240, 1.99, 'intothewild.jpg', 'tracks/Rooler & Atmozfears - INTO THE WILD (Official Intents Festival 2024 Anthem) (Extended Mix).mp3', 59, 89, 'previews/preview_17_d8e36872-4b0c-4301-85df-35a85ff59ae4.mp3'),
(18, 3, NULL, 'Rooler & Sickmode & D-Block & S-te-Fan - LOVE THE WAY(Extended Mix)', 155, '2026-03-05', 240, 1.99, 'lovetheway.jpg', 'tracks/Rooler & Sickmode & D-Block & S-te-Fan - LOVE THE WAY(Extended Mix).mp3', 98, 128, 'previews/preview_18_24e5f2d2-2d84-4f79-8050-71677d725698.mp3'),
(19, 3, NULL, 'Rooler & Sickmode & Paul Elstak - TAKE ME AWAY (Extended Mix)', 180, '2026-03-05', 240, 1.99, 'takemeaway.jpg', 'tracks/Rooler & Sickmode & Paul Elstak - TAKE ME AWAY (Extended Mix).mp3', 106, 136, 'previews/preview_19_6a97165f-9cf1-4511-b400-9091f7490213.mp3'),
(20, 1, NULL, 'Sickmode - GO Crazy(Extended Mix)', 160, '2026-03-05', 240, 1.99, 'gocrazy.jpg', 'tracks/Sickmode - GO Crazy(Extended Mix).mp3', 47, 77, 'previews/preview_20_f0311aae-c832-4192-96a5-0ab124f25d88.mp3'),
(21, 3, NULL, 'Sickmode & Rooler - CLUB BANGER (Extended Mix)', 155, '2026-03-05', 240, 1.99, 'clubbanger.jpg', 'tracks/Sickmode & Rooler - CLUB BANGER (Extended Mix).mp3', 77, 107, 'previews/preview_21_19b187a6-8837-408e-827e-e087fd046aec.mp3'),
(23, 3, NULL, 'Sound Rush &amp; Drean &amp; Rooler - RUNAWAY (Extented Mix) ', 155, '2026-03-05', 210, 1.99, 'roolerrunaway.jpg', 'tracks/Sound Rush &amp; Drean &amp; Rooler - RUNAWAY (Extented Mix) .mp3', 0, 30, 'previews/preview_23_a6053258-d7d6-4ba1-b0eb-3a9170270eda.mp3'),
(24, 2, NULL, 'Subtronics - Amnesia (Cyclops Flip)', 140, '2026-03-05', 210, 1.99, 'cyclopamnesia.jpg', 'tracks/Subtronics - Amnesia (Cyclops Flip).mp3', 36, 66, 'previews/preview_24_4b9e5b47-90a4-4600-bce2-aa724491046c.mp3'),
(25, 2, NULL, 'Subtronics - Anxious ', 140, '2026-03-05', 210, 1.99, 'subtronicsaxiousjpg.jpg', 'tracks/Subtronics - Anxious .mp3', 0, 30, 'previews/preview_25_0ab1f5e2-031a-4090-86b4-1e2ed895e12f.mp3'),
(26, 2, NULL, 'Subtronics - Gangstas', 140, '2026-03-05', 210, 1.99, 'subtronicsgangstas.jpg', 'tracks/Subtronics - Gangstas .mp3', 61, 91, 'previews/preview_26_f1d89b58-5c4a-4fd6-8b16-8ee5e3eb612f.mp3'),
(27, 2, NULL, 'Subtronics - Infinity (feat. Grabbitz)', 140, '2026-03-05', 210, 1.99, 'subronicsinfinity.jpg', 'tracks/Subtronics - Infinity (feat. Grabbitz) .mp3', 77, 107, 'previews/preview_27_0e8fd313-b0a2-40d8-9085-0927042205b1.mp3'),
(28, 2, NULL, 'Subtronics - MetaFractal VIP', 140, '2026-03-05', 210, 1.99, 'metalfractalVIP.jpg', 'tracks/Subtronics - MetaFractal VIP .mp3', 54, 84, 'previews/preview_28_57c5bf89-fd20-431d-af25-07d1abdc1573.mp3'),
(29, 2, NULL, 'Subtronics - Nitrous Mafia', 140, '2026-03-05', 210, 1.99, 'nitrousmafia.jpg', 'tracks/Subtronics - Nitrous Mafia .mp3', 32, 62, 'previews/preview_29_06c2e036-a97c-4931-af16-7932e11cf897.mp3'),
(30, 2, NULL, 'Subtronics feat. CREG - Antidote (Midnight Coffee) ', 140, '2026-03-05', 210, 1.99, 'subtronicsantidote.jpg', 'tracks/Subtronics feat. CREG - Antidote (Midnight Coffee) .mp3', 79, 109, 'previews/preview_30_66c11df0-e5b6-4182-85ac-43b096f4c315.mp3'),
(31, 2, NULL, 'Subtronics feat. Jem Cooke - By A Thread ', 140, '2026-03-05', 210, 1.99, 'subtronicsbyathread.jpg', 'tracks/Subtronics feat. Jem Cooke - By A Thread .mp3', 0, 30, 'previews/preview_31_aa3ebc27-e62a-4130-b9b3-3ba093605014.mp3'),
(32, 2, NULL, 'Zeds Dead, Subtronics feat. Flowdan - Gassed Up', 140, '2026-03-05', 210, 1.99, 'subtronicsgassedup.jpg', 'tracks/Zeds Dead, Subtronics feat. Flowdan - Gassed Up .mp3', 58, 88, 'previews/preview_32_143054bf-45b1-41af-8da7-c7500b95321d.mp3'),
(33, 7, 2, 'the floor - HAAi remix', 117, '1970-01-01', 230, 1.99, 'track-covers/1y1v2coQkF9VAbUxutTEfLbHTkMQevyWFu0oXjVh.jpg', 'tracks/the_floor_haai_remix_so7mpjjt.mp3', 78, 108, 'previews/preview_33_d461fd61-cba7-411d-abee-79ef0b13475f.mp3'),
(34, 7, NULL, 'Hamdi remix', 124, '1970-01-01', 196, 1.99, 'track-covers/ljMSXFDZvgjQaKeysLXbAJfxERpMmjTYhx97H7R2.jpg', 'tracks/hamdi_remix_g8rvbnpx.mp3', 48, 78, 'previews/preview_34_b9df5c02-09ef-4120-9cf8-87ad41bb0b9f.mp3'),
(35, 8, NULL, 'Prenses (Remix)', 100, '2023-06-08', 207, 1.99, 'track-covers/UsKCyXhpQxVA5ZN3qZN9ok4Bgz3JHDovbviAjzAA.jpg', 'tracks/prenses_remix_okmxoeml.mp3', 76, 106, 'previews/preview_35_87cc018a-8be5-4804-9e34-29fc5d4dffad.mp3'),
(36, 6, NULL, 'Benzedes Mers (KARAMELA)', 139, '2023-01-01', 160, 1.99, 'track-covers/MGHxcYOSYS2qpes8NahfyTdnBnfQo76OLHoOTGQy.jpg', 'tracks/benzedes_mers_karamela_91h3ymir.mp3', 99, 129, 'previews/preview_36_8eca9cdd-524b-4f78-914c-1264cedf7275.mp3'),
(37, 11, NULL, 'SINKIDX', 108, '2026-01-01', 107, 1.99, 'track-covers/SjwToUUMqo33Rz0hsa1EPcqUQnm7N5LdE7Rh5thY.jpg', 'tracks/sinkidx_ty63hifu.mp3', 36, 66, 'previews/preview_37_d46f5b7a-7b5f-451b-8438-c243e8093d4a.mp3'),
(38, 2, 3, 'Gas Pedal (ft Sage The Gemini) [Extended Mix]', 117, '2024-01-01', 153, 1.99, 'track-covers/YxLtiY7rr60n24PfyTXieMqcPa7g80znNyHInUnn.jpg', 'tracks/gas_pedal_ft_sage_the_gemini_extended_mix_oqcdem98.mp3', 100, 130, 'previews/preview_38_426365e2-3c48-4976-b0f9-8ccd2a78a19e.mp3'),
(39, 10, NULL, '##', 120, '2024-01-01', 160, 1.99, 'track-covers/CvaXfdtqN9wqOpfSvarOKLQPy95OoiPsKhp9MZwH.jpg', 'tracks/track_39_uolgntkh.mp3', 15, 45, 'previews/preview_39_1adec47a-84dd-4859-bed3-f74dc8ecb63e.mp3'),
(40, 1, NULL, 'IN MY HEAD (Original Mix)', 160, '2025-01-01', 197, 1.99, 'track-covers/Gad535nt9A8llOYp9oP1jxiQ4bd8BtKDfM34V282.jpg', 'tracks/in_my_head_original_mix_te89xskw.mp3', 23, 53, 'previews/preview_40_54b27005-92c1-49ec-8d00-f80c37e09e7e.mp3'),
(41, 10, NULL, '7777777', 130, '2025-01-01', 92, 1.99, 'track-covers/rU25QhtC5zveFhLXqU566LFEVWeAeUAdHU20BSL0.jpg', 'tracks/7777777_y7onghnn.mp3', 16, 46, 'previews/preview_41_3ede1ee5-9006-4c4c-a782-46708039d4bc.mp3'),
(42, 10, NULL, '911 CARRERA', 85, '2024-01-01', 104, 1.99, 'track-covers/otzgfjankgPNZGUcoa9bT2W539lVd2P8SIUsYjy8.jpg', 'tracks/911_carrera_faez6uht.mp3', 29, 59, 'previews/preview_42_b3acef3a-6dd9-40f8-bf99-d6a74a64fe29.mp3'),
(43, 10, NULL, 'AŞKIM TRAP', 128, '2024-01-01', 139, 1.99, 'track-covers/1FAH1L9WVIrnAAZY6jKuzMjJWe7qe476RLhwGFo7.jpg', 'tracks/askim_trap_deg35naw.mp3', 104, 134, 'previews/preview_43_d7469124-4fe3-4194-8193-8093d384912b.mp3'),
(44, 1, NULL, 'We Got the Moves - Rooler Remix', 150, NULL, 203, 1.99, 'track-covers/TJtFqpYuvv02kvfGXQGATNxUUtc2VyWGcvFScK2l.jpg', 'tracks/we_got_the_moves_rooler_remix_vxa3o2kr.mp3', 104, 134, 'previews/preview_44_869a2ca8-b6d8-4457-98ae-0a9e3862964f.mp3'),
(45, 1, NULL, 'ANNOYING MUSIC (Extended Mix)', 160, '2025-01-01', 197, 1.99, 'track-covers/QUzYu5XI7RbQnzrQPhLt6WJtBdELVUqvOeN1qq5z.jpg', 'tracks/annoying_music_extended_mix_k4tznq1o.mp3', 156, 186, 'previews/preview_45_98aafd29-1c27-4bb4-bf9b-156c8957b1e1.mp3'),
(46, 1, NULL, 'Techno Pieps (Extended Mix)', 155, '2025-01-01', 160, 1.99, 'track-covers/3K4dA66j240eSfLu99oSLAOeqIMd4VaavaFmCf2d.jpg', 'tracks/techno_pieps_extended_mix_fyxj2rlx.mp3', 61, 91, 'previews/preview_46_2b041543-97cc-4618-974f-1b8971f9f544.mp3'),
(47, 1, NULL, 'MOVE IT (Extended Mix)', 160, '2024-01-01', 162, 1.99, 'track-covers/1mbXp1BMb1GwjnYUdAKzLoNO7NOoNCQ9qXhW8rP9.jpg', 'tracks/move_it_extended_mix_72detxpr.mp3', 46, 76, 'previews/preview_47_e4123685-90d2-4c90-b146-3176073c64cc.mp3'),
(48, 3, NULL, 'LET DA BASS!! (Extended Mix)', 160, '2026-01-01', 180, 1.99, 'track-covers/oLprlqVajC9XVE1TKEXPJgf6yTieyLs4RfOZzzxO.jpg', 'tracks/let_da_bass_extended_mix_csw6cmg8.mp3', 145, 175, 'previews/preview_48_3ab99e54-8464-4a7e-830a-b63f38ae1aee.mp3'),
(49, 1, NULL, 'WHAT THA HELLY (SOMEONE CALL THE AMBULANCE) (Extended Mix)', 170, '2025-01-01', 200, 1.99, 'track-covers/w08NCApO6oIj7mUIBOaZzuMW6u8XblDs4XELygDq.jpg', 'tracks/what_tha_helly_someone_call_the_ambulance_extended_mix_7p9wup17.mp3', 72, 102, 'previews/preview_49_8858f891-4d13-436f-a7f7-36078a6bcebd.mp3'),
(50, 1, NULL, 'TOO ANGRY (Extended Mix)', 160, '2024-01-01', 255, 1.99, 'track-covers/28cgCaGN6lp9lhz9K1XMtT9Uglhf1UyiiQdPWVy2.jpg', 'tracks/too_angry_extended_mix_vbhpxxje.mp3', 85, 115, 'previews/preview_50_1ff0bab3-8246-4dfb-9e47-ee83d5b455e5.mp3'),
(51, 1, NULL, 'Love Don''t Let Me Go (Original Mix)', 160, '2024-07-25', 201, 1.99, 'track-covers/U3ecfXwrmWgmZkGTVIec4A8F5x0gDq61abf0YKev.jpg', 'tracks/love_dont_let_me_go_original_mix_5ojpa9rn.wav', 50, 80, 'previews/preview_51_ae531195-4428-4bb4-b63d-b232b31447a2.mp3'),
(52, 1, NULL, 'TOO COLD (Extended Mix)', 160, '2021-01-01', 212, 1.99, 'track-covers/zq4Mo2tdxOKRFzdJ0H8fYJcMOJGm6gF4spEnPt2O.jpg', 'tracks/too_cold_extended_mix_chzp59ol.mp3', 92, 122, 'previews/preview_52_a93b664b-9174-4801-884d-1c3a312f7707.mp3'),
(53, 3, NULL, 'Drop The Bomb (Pro Mix)', 160, NULL, 192, 1.99, 'track-covers/MI66OZQF0tPufeaBLPPpvhksuNvtbZoQkJNGEgWc.jpg', 'tracks/drop_the_bomb_pro_mix_6zbffwnb.mp3', 48, 78, 'previews/preview_53_92168f48-9149-40e5-838b-007f606f272d.mp3'),
(54, 1, NULL, 'WE BURNING THE Dancefloor (Extended Mix)', 160, NULL, 249, 1.99, 'track-covers/leQMF3GDqx0epdSx0BMwoFUceeVRL6mBh40NMFRF.jpg', 'tracks/we_burning_the_dancefloor_extended_mix_onanwwwn.mp3', 74, 104, 'previews/preview_54_43a0ece5-2be0-42f7-9c19-e748bff8bce6.mp3'),
(55, 1, NULL, 'DREAM OF U!! (Extended Mix)', 160, '2025-01-01', 177, 1.99, 'track-covers/sVMNuhxmEJQajeDeLqFhsY6ljCnbjuBwfZ4m1Bh8.jpg', 'tracks/dream_of_u_extended_mix_oadkadyk.mp3', 42, 72, 'previews/preview_55_21a5bd49-a3e7-464c-8e3a-f90a8e15aca2.mp3'),
(56, 1, NULL, 'YEAHBOIII (Extended Mix)', 160, '2024-01-01', 215, 1.99, 'track-covers/n34w7sCaWcjKmU17GBzEyegCwRaVrIdvgAc5b2mU.jpg', 'tracks/yeahboiii_extended_mix_poikakr6.mp3', 31, 61, 'previews/preview_56_bad23c67-ba8c-4b7f-8bb9-75199234c503.mp3'),
(57, 1, NULL, 'RAVE LOVE (Extended Mix)', 160, '2022-01-01', 228, 1.99, 'track-covers/1oMuUUDpcna6b0IESymzfsm8FpexK5qIAbzEoOrZ.jpg', 'tracks/rave_love_extended_mix_hp8ye8fq.mp3', 138, 168, 'previews/preview_57_7b866bb0-10a7-4d95-9315-930696a43784.mp3'),
(58, 1, NULL, 'HYPNOTISED (Extended Mix)', 160, '2024-01-01', 165, 1.99, 'track-covers/h4DdCF0MbeDoT1NNPwWohmYhkvexDGlRDnE7QPo5.jpg', 'tracks/hypnotised_extended_mix_cc2nipmc.mp3', 54, 84, 'previews/preview_58_a0d14e22-0220-4567-bc78-acb3bdb94102.mp3'),
(59, 1, NULL, 'Rise (Extended Mix]', 155, '2024-01-01', 200, 1.99, 'track-covers/gswsh8XzgAvuYEefwQVHsplb9jMuyc5nXM00592j.jpg', 'tracks/rise_extended_mix_pn7r9pqv.mp3', 79, 109, 'previews/preview_59_7ba931c4-5b66-478c-af02-3198d6fdd000.mp3'),
(60, 1, NULL, 'Feel So Good (Original Mix)', 155, '2023-04-28', 243, 1.99, 'track-covers/UjYpytxdkpUq7R2RCtITKG4ZCKivDkUxefXodita.jpg', 'tracks/feel_so_good_original_mix_fifvf6ct.mp3', 111, 141, 'previews/preview_60_a4265504-37cd-4648-9256-7e20caaeb918.mp3'),
(61, 1, 1, 'Beyond The Horizon (Extended Mix)', 160, '2025-01-01', 221, 1.99, 'track-covers/hV0uwUgje1yETqLa1xpmdU4iL3bnnxC20ulydeJb.jpg', 'tracks/beyond_the_horizon_extended_mix_psytxl6k.mp3', 95, 125, 'previews/preview_61_4a88503b-8650-438c-a7e7-e68afe3a627b.mp3'),
(62, 1, 1, 'We Own The Night (Extented Mix)', 160, '2025-01-01', 236, 1.99, 'track-covers/8elfZ1LgbNRzyIKTz1ybsphvgM2ZKgNmnPOPUmk3.jpg', 'tracks/we_own_the_night_extented_mix_lmjoq9xw.mp3', 105, 135, 'previews/preview_62_edfc54c2-9133-403a-a375-58b73ff9cdf0.mp3'),
(63, 1, 1, 'Aliens On Acid (Extended Mix)', 160, '2025-01-01', 234, 1.99, 'track-covers/6TSCmJDL5Q1mPGqDic7NZT23kupkQSt0mdZ8Ky8M.jpg', 'tracks/aliens_on_acid_extended_mix_5d3zqgh8.mp3', 172, 202, 'previews/preview_63_c62632c3-0aec-4808-ae31-102f38cb0fdd.mp3'),
(64, 1, 1, 'Lightyears & Nightmares (Extended Mix)', 160, '2025-01-01', 198, 1.99, 'track-covers/3gPq9WcUfggnZjhaCKWf2dZQedgN3yOf3A5bhHZ6.jpg', 'tracks/lightyears_nightmares_extended_mix_qg7ukklk.mp3', 77, 107, 'previews/preview_64_9eb30e3f-7b1b-4202-9dbd-6627d0a95dd4.mp3'),
(65, 1, 1, 'Serenity (Extended Mix)', 160, '2025-01-01', 216, 1.99, 'track-covers/MRQ8IjayPKoopWzlzdUyHlxgH32aGfhsnyLfbpNT.jpg', 'tracks/serenity_extended_mix_3ejuhacl.mp3', 70, 100, 'previews/preview_65_64415d96-fe97-45ec-9598-0366b8aee0d8.mp3'),
(66, 1, 1, 'Closer To Heaven (Extented Mix)', 160, '2025-01-01', 203, 1.99, 'track-covers/xk4SQBmft7rY7VhUf0t6SjUWYdWpbKGBwypcDCTk.jpg', 'tracks/closer_to_heaven_extented_mix_kopvihe3.mp3', 65, 95, 'previews/preview_66_6b952273-f204-481d-8f8c-7c5105a94a7b.mp3'),
(67, 1, 1, 'Life or Death [Ecstatic Remix](Extended Mix)', 117, '2025-01-01', 198, 1.99, 'track-covers/dwYllu5R5KD5kcpAhSKjXsDBZn4WqegKtDm5bElf.jpg', 'tracks/life_or_death_ecstatic_remixextended_mix_3bjijmos.mp3', 61, 91, 'previews/preview_67_68f4918d-71a7-4541-933a-9a7ae5dca842.mp3'),
(68, 1, 1, 'Come Together (Extended Mix)', 160, '2025-01-01', 255, 1.99, 'track-covers/UF3mLdYfydYwaSy1JBKWenwUaFaNkft32RzgSKEI.jpg', 'tracks/come_together_extended_mix_fgvqwnac.mp3', 134, 164, 'previews/preview_68_37a8885d-cb9c-49b6-a3ed-a418c432a3fc.mp3'),
(69, 1, 1, 'Futurepower (Vexxed Remix) (Extended Mix)', 160, '2025-01-01', 226, 1.99, 'track-covers/wAwQ9bHvX7Bf112vcDBnDnWtiGFcQu4nLZCfz0IL.jpg', 'tracks/futurepower_vexxed_remix_extended_mix_btd8pb82.mp3', 88, 118, 'previews/preview_69_1c7d1e37-4641-4271-8734-fdf7c9dc2ad1.mp3'),
(70, 1, 1, 'Burning Down (Rebelion Edit) (Extended Mix)', 160, '2025-01-01', 132, 1.99, 'track-covers/jd1zF04g10msxLFF2g1Qi37xqE2S8oz460Zaix2s.jpg', 'tracks/burning_down_rebelion_edit_extended_mix_ohk0zllw.mp3', 82, 112, 'previews/preview_70_f5c3dbad-8769-489d-b1ed-efd62032cbc8.mp3'),
(71, 1, 1, 'Rebel Fever (Extended Mix)', 160, '2025-01-01', 204, 1.99, 'track-covers/gfFcUWXLdudKTqsDBjuZDwH0tX9GRUlGx5qgXXm4.jpg', 'tracks/rebel_fever_extended_mix_g07a6b1a.mp3', 74, 104, 'previews/preview_71_1a46628b-e306-43c7-8596-c5dc6f9b4dae.mp3'),
(72, 1, 1, 'Magic (Extended Mix)', 160, '2025-01-01', 230, 1.99, 'track-covers/O7ng1zaWWGZD0LC0XkMf5LPegdYDPAgCknIJCXs7.jpg', 'tracks/magic_extended_mix_u6ameitp.mp3', 45, 75, 'previews/preview_72_c173f83f-3eaf-426c-bd20-18fd669c6403.mp3'),
(73, 1, 1, 'In Control (Dual Damage Edit) (Extended Mix)', 160, '2025-01-01', 168, 1.99, 'track-covers/RKM55wgLhlQmzhECDh5vVKdnbeRCoGXmQywzcFZM.jpg', 'tracks/in_control_dual_damage_edit_extended_mix_yy456b40.mp3', 57, 87, 'previews/preview_73_0918c920-1a59-4085-949c-231cc52b6c13.mp3'),
(74, 1, 1, 'Lights Off (Extented Mix)', 160, '2025-01-01', 81, 1.99, 'track-covers/IDPh0BXVD1vHBMcH7iToWehxKfcuewbG3uOtSZrR.jpg', 'tracks/lights_off_extented_mix_4xgyb1lu.mp3', 37, 67, 'previews/preview_74_167ecc21-2d31-4e45-a1ca-0585a0dd83ca.mp3'),
(75, 14, 1, 'A Message From Beyond (Original Mix)', 208, '2025-01-01', 112, 1.99, 'track-covers/ahTWmfRfnAZVVg1O5rW7eMEomScJt5gHjrGlgou8.jpg', 'tracks/a_message_from_beyond_original_mix_oql3gsmx.mp3', 58, 88, 'previews/preview_75_3d0dcebd-8383-42c8-a734-e65a93c8c6aa.mp3'),
(76, 3, NULL, 'Stuck In My Head! (Extended Mix)', 176, '2023-01-01', 210, 1.99, 'track-covers/NODmRqwMtNLt6GBx7Y2PbKIrk4g5MUBtwoWUXlSp.jpg', 'tracks/stuck_in_my_head_extended_mix_6s3goob9.mp3', 48, 78, 'previews/preview_76_09bedcde-68dc-4939-80b6-c9d33c6065f7.mp3'),
(77, 7, 2, 'Mc Dricka remix', 128, '1970-01-01', 188, 1.99, 'track-covers/FHLnQttSefZMtpMA6sgREXcMxwvU8YV4QUueFSl9.jpg', 'tracks/mc_dricka_remix_z36bh7a2.mp3', 42, 72, 'previews/preview_77_41509ddb-115e-4d97-b8a1-4728e11f5f6d.mp3'),
(78, 2, NULL, 'Next To You', 150, NULL, 196, 1.99, 'track-covers/cyiRJHChT8TnmjvMx58ge42Hw9Z92khQQ1G8JSX7.jpg', 'tracks/next_to_you_e05if9rz.mp3', 88, 118, 'previews/preview_78_3d265967-7920-4f55-9d4f-7cf54502b3d0.mp3'),
(79, 1, NULL, 'Woops (Anderex Edit Extended)', 160, NULL, 186, 1.99, 'track-covers/VL6HaZBsCyIudamjtbGm6yQqai93AhTrbrXdDzM5.jpg', 'tracks/dj_bountyhunter_woops_anderex_edit_extended_ew3zmuze.wav', 52, 82, 'previews/preview_79_bf57138a-1644-412c-9f5a-b0d45af01f0a.mp3'),
(80, 2, NULL, 'BACKBONE SUBTRONICS BOOTLEG + YASUO', 117, '2025-01-01', 110, 1.99, 'track-covers/XvSaJJptT8hqjnblu09IAkqGPPLueMNshD64KGCP.jpg', 'tracks/subtronics_backbone_subtronics_bootleg_yasuo_ros1if9h.mp3', 40, 70, 'previews/preview_80_f7fa9f37-c53e-4a2b-a325-e819f4b18c64.mp3'),
(81, 15, NULL, 'Cinema (EOTI edit)', 117, NULL, 179, 1.99, 'track-covers/N2NebcfQrPuZDCm12bEhteEwGOPvguksuDpcFOtN.jpg', 'tracks/explorers_of_the_internet_cinema_eoti_edit_yfjspajo.wav', 19, 49, 'previews/preview_81_73c5a8d7-c1b5-4049-aa68-efa3be92193d.mp3'),
(82, 1, 3, 'askim sssssssssstrap deg35naw', 117, '2024-01-01', 139, 1.99, 'track-covers/nwmv5C7o4R8sQboA0ztG8zdGIdCzLbxrieH6Wtbm.jpg', 'tracks/askim_trap_deg35naw_v0eowakq.mp3', 33, 63, 'previews/preview_82_35129847-4e3e-45a3-9d41-0934b76c1d06.mp3'),
(83, 8, NULL, '911 carrera faez6uht', 85, '2024-01-01', 104, 1.99, 'track-covers/4cxzMcAtPc5HeflOkrfYiEMW5oMKxXjaxWqzzXLr.jpg', 'tracks/911_carrera_faez6uht_95nnoiml.mp3', 0, 30, 'previews/preview_83_60f20feb-bbe5-42f7-bbf8-51bbcd06acf8.mp3');

-- 
-- Dumping data for table carts
--
INSERT INTO carts VALUES
(5, 3, '2026-03-24'),
(7, 2, '2026-03-25');

-- 
-- Dumping data for table track_genres
--
INSERT INTO track_genres VALUES
(52, 1),
(57, 1),
(24, 2),
(27, 2),
(83, 8),
(83, 9),
(27, 15);

-- 
-- Dumping data for table track_artists
--
INSERT INTO track_artists VALUES
(1, 1),
(4, 1),
(15, 1),
(24, 1),
(25, 1),
(26, 1),
(27, 1),
(28, 1),
(29, 1),
(30, 1),
(31, 1),
(32, 1),
(38, 1),
(80, 1),
(2, 2),
(3, 2),
(5, 2),
(6, 2),
(7, 2),
(8, 2),
(9, 2),
(10, 2),
(11, 2),
(12, 2),
(13, 2),
(47, 2),
(49, 2),
(51, 2),
(16, 3),
(17, 3),
(18, 3),
(19, 3),
(21, 3),
(23, 3),
(44, 3),
(45, 3),
(48, 3),
(50, 3),
(52, 3),
(55, 3),
(20, 4),
(52, 4),
(54, 4),
(56, 4),
(57, 4),
(14, 5),
(40, 5),
(57, 5),
(58, 5),
(82, 5),
(39, 7),
(41, 7),
(42, 7),
(43, 7),
(83, 7),
(35, 13),
(33, 14),
(34, 14),
(77, 14),
(36, 17),
(37, 18),
(46, 20),
(53, 27),
(72, 28),
(59, 31),
(60, 31),
(61, 32),
(62, 32),
(63, 32),
(64, 32),
(65, 32),
(66, 32),
(67, 32),
(68, 32),
(69, 32),
(70, 32),
(71, 32),
(73, 32),
(74, 32),
(75, 32),
(76, 37),
(79, 37),
(78, 40),
(81, 43),
(24, 44);

-- 
-- Dumping data for table sessions
--
INSERT INTO sessions VALUES
('PBYUlCq0Bp2sXWuAv2faoTxq3hcWdWMALk961qn4', NULL, '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36', 'YTozOntzOjY6Il90b2tlbiI7czo0MDoiN1pObkNUak5meU15TTVnRzZiYndlOHF5VDJvWHBxM210d0l2ZjkzaCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MjE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMCI7czo1OiJyb3V0ZSI7Tjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==', 1774262456);

-- 
-- Dumping data for table recommendation_links
--
INSERT INTO recommendation_links VALUES
(1, 'SoundCloud recommendation', 'https://soundcloud.com/officialrevelationnl/tnt-darren-styles-hard-beat', 0, '2026-03-19 09:39:10', '2026-03-19 09:39:10');

-- 
-- Dumping data for table personal_access_tokens
--
INSERT INTO personal_access_tokens VALUES
(3, 'App\\Models\\User', 1, '1day-role:1', 'eb2c5e3d395ec37a792710971f619a7c62b8a4c752b93fee898a4509413e6e72', '["*"]', '2026-03-19 12:41:03', '2026-03-20 11:55:03', '2026-03-19 11:55:03', '2026-03-19 12:41:03'),
(27, 'App\\Models\\User', 2, '1day-role:2', 'a72b2c5b63e415eedb983613debed6e40a0febacc629a82cdd1052eda7e812cd', '["usersme:get","usersme:patch","usersme:updatePassword","usersme:delete","carts:self:get","carts:self:post","carts:self:delete","cart-items:self:get","cart-items:self:post","cart-items:self:patch","cart-items:self:delete","checkout:self:post"]', '2026-03-31 08:35:44', '2026-04-01 06:26:03', '2026-03-31 06:26:03', '2026-03-31 08:35:44');

-- 
-- Dumping data for table password_reset_tokens
--
-- Table doomshop.password_reset_tokens does not contain any data (it is empty)

-- 
-- Dumping data for table migrations
--
INSERT INTO migrations VALUES
(43, '0001_01_01_000000_create_users_table', 1),
(44, '0001_01_01_000001_create_cache_table', 1),
(45, '0001_01_01_000002_create_jobs_table', 1),
(46, '2025_11_04_102115_create_personal_access_tokens_table', 1),
(47, '2025_11_18_081107_add_role_to_users_table', 1),
(48, '2025_11_24_110131_create_genres_table', 1),
(49, '2025_11_24_114059_create_artists_table', 1),
(50, '2025_11_24_114447_create_tracks_table', 1),
(51, '2025_11_24_115002_create_track_artists_table', 1),
(52, '2026_03_05_180000_create_carts_table', 1),
(53, '2026_03_05_180100_create_cart_items_table', 1),
(54, '2026_03_06_120000_add_preview_fields_to_tracks_table', 1),
(55, '2026_03_07_200000_create_track_genres_table', 1),
(56, '2026_03_07_210000_create_liveshow_links_table', 1),
(57, '2026_03_07_220000_create_recommendation_links_table', 1),
(58, '2026_03_08_120000_add_track_price_eur_to_tracks_table', 1),
(59, '2026_03_08_150000_add_unique_indexes_for_catalog_entities', 1),
(60, '2026_03_08_160000_create_albums_table', 1),
(61, '2026_03_08_160100_add_album_id_to_tracks_table', 1),
(62, '2026_03_08_170000_add_album_id_to_cart_items_table', 1),
(63, '2026_03_08_170100_make_track_id_nullable_on_cart_items', 1);

-- 
-- Dumping data for table liveshow_links
--
INSERT INTO liveshow_links VALUES
(1, 'YouTube video (3BrZlwqYCIc)', 'https://www.youtube.com/watch?v=3BrZlwqYCIc&t=2850s', 0, '2026-03-19 09:39:10', '2026-03-19 09:39:10'),
(2, 'YouTube video (jFswMC5kJCs)', 'https://www.youtube.com/watch?v=jFswMC5kJCs&', 0, '2026-03-19 09:39:10', '2026-03-19 09:39:10'),
(3, 'YouTube video (GuRVcYVIEpk)', 'https://www.youtube.com/watch?v=GuRVcYVIEpk', 0, '2026-03-19 09:39:10', '2026-03-19 09:39:10'),
(4, 'YouTube video (0uGTATjvSk4)', 'https://www.youtube.com/watch?v=0uGTATjvSk4&', 0, '2026-03-19 09:39:10', '2026-03-19 09:39:10'),
(5, 'YouTube video (PJUPwtAYLzs)', 'https://www.youtube.com/watch?v=PJUPwtAYLzs', 0, '2026-03-19 09:39:10', '2026-03-19 09:39:10'),
(6, 'YouTube video (FypOaUjfs0U)', 'https://www.youtube.com/watch?v=FypOaUjfs0U&t', 0, '2026-03-19 09:39:10', '2026-03-19 09:39:10'),
(7, 'YouTube video (Jn3_oozDoAw)', 'https://www.youtube.com/watch?v=Jn3_oozDoAw&t', 0, '2026-03-19 09:39:10', '2026-03-19 09:39:10'),
(8, 'YouTube video (2yfyPeAEV3A)', 'https://www.youtube.com/watch?v=2yfyPeAEV3A&t', 0, '2026-03-19 09:39:10', '2026-03-19 09:39:10'),
(9, 'YouTube video (43A65yV0gr8)', 'https://www.youtube.com/watch?v=43A65yV0gr8&', 0, '2026-03-19 09:39:10', '2026-03-19 09:39:10');

-- 
-- Dumping data for table job_batches
--
-- Table doomshop.job_batches does not contain any data (it is empty)

-- 
-- Dumping data for table jobs
--
-- Table doomshop.jobs does not contain any data (it is empty)

-- 
-- Dumping data for table failed_jobs
--
-- Table doomshop.failed_jobs does not contain any data (it is empty)

-- 
-- Dumping data for table cart_items
--
INSERT INTO cart_items VALUES
(2, 7, 61, NULL, 1),
(3, 7, 76, NULL, 1),
(4, 7, 49, NULL, 1);

-- 
-- Dumping data for table cache_locks
--
-- Table doomshop.cache_locks does not contain any data (it is empty)

-- 
-- Dumping data for table cache
--
-- Table doomshop.cache does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;