--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2026.01.23. 7:51:49
-- Server version: 5.7.44
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS school;

CREATE DATABASE IF NOT EXISTS school
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE school;

--
-- Create table `schoolclasses`
--
CREATE TABLE IF NOT EXISTS schoolclasses (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  osztalyNev VARCHAR(10) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 25,
AVG_ROW_LENGTH = 682,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `schoolclasses_osztalynev_unique` on table `schoolclasses`
--
ALTER TABLE schoolclasses 
  ADD UNIQUE INDEX schoolclasses_osztalynev_unique(osztalyNev);

--
-- Create table `students`
--
CREATE TABLE IF NOT EXISTS students (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  diakNev VARCHAR(191) NOT NULL,
  schoolclassId BIGINT(20) UNSIGNED NOT NULL,
  neme TINYINT(1) NOT NULL DEFAULT 1,
  iranyitoszam VARCHAR(191) DEFAULT NULL,
  lakHelyseg VARCHAR(191) DEFAULT NULL,
  lakCim VARCHAR(191) DEFAULT NULL,
  szulHelyseg VARCHAR(191) DEFAULT NULL,
  szulDatum DATE DEFAULT NULL,
  igazolvanyszam VARCHAR(191) DEFAULT NULL,
  atlag DECIMAL(2, 1) DEFAULT NULL,
  osztondij DECIMAL(10, 0) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 673,
AVG_ROW_LENGTH = 195,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `students_igazolvanyszam_unique` on table `students`
--
ALTER TABLE students 
  ADD UNIQUE INDEX students_igazolvanyszam_unique(igazolvanyszam);

--
-- Create foreign key
--
ALTER TABLE students 
  ADD CONSTRAINT students_schoolclassid_foreign FOREIGN KEY (schoolclassId)
    REFERENCES schoolclasses(id);

--
-- Create table `sports`
--
CREATE TABLE IF NOT EXISTS sports (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  sportNev VARCHAR(75) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 31,
AVG_ROW_LENGTH = 528,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `sports_sportnev_unique` on table `sports`
--
ALTER TABLE sports 
  ADD UNIQUE INDEX sports_sportnev_unique(sportNev);

--
-- Create table `playingsports`
--
CREATE TABLE IF NOT EXISTS playingsports (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  studentId BIGINT(20) UNSIGNED NOT NULL,
  sportId BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 675,
AVG_ROW_LENGTH = 97,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `playingsports_studentid_sportid_unique` on table `playingsports`
--
ALTER TABLE playingsports 
  ADD UNIQUE INDEX playingsports_studentid_sportid_unique(studentId, sportId);

--
-- Create foreign key
--
ALTER TABLE playingsports 
  ADD CONSTRAINT playingsports_sportid_foreign FOREIGN KEY (sportId)
    REFERENCES sports(id);

--
-- Create foreign key
--
ALTER TABLE playingsports 
  ADD CONSTRAINT playingsports_studentid_foreign FOREIGN KEY (studentId)
    REFERENCES students(id);

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL,
  role INT(11) NOT NULL DEFAULT 3,
  email_verified_at TIMESTAMP NULL DEFAULT NULL,
  password VARCHAR(191) NOT NULL,
  remember_token VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `users_email_unique` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX users_email_unique(email);

--
-- Create table `sessions`
--
CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(191) NOT NULL,
  user_id BIGINT(20) UNSIGNED DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  payload LONGTEXT NOT NULL,
  last_activity INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `sessions_last_activity_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_last_activity_index(last_activity);

--
-- Create index `sessions_user_id_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_user_id_index(user_id);

--
-- Create table `personal_access_tokens`
--
CREATE TABLE IF NOT EXISTS personal_access_tokens (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  tokenable_type VARCHAR(191) NOT NULL,
  tokenable_id BIGINT(20) UNSIGNED NOT NULL,
  name TEXT NOT NULL,
  token VARCHAR(64) NOT NULL,
  abilities TEXT DEFAULT NULL,
  last_used_at TIMESTAMP NULL DEFAULT NULL,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 85,
AVG_ROW_LENGTH = 303,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `personal_access_tokens_expires_at_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_expires_at_index(expires_at);

--
-- Create index `personal_access_tokens_token_unique` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD UNIQUE INDEX personal_access_tokens_token_unique(token);

--
-- Create index `personal_access_tokens_tokenable_type_tokenable_id_index` on table `personal_access_tokens`
--
ALTER TABLE personal_access_tokens 
  ADD INDEX personal_access_tokens_tokenable_type_tokenable_id_index(tokenable_type, tokenable_id);

--
-- Create table `password_reset_tokens`
--
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  email VARCHAR(191) NOT NULL,
  token VARCHAR(191) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (email)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `migrations`
--
CREATE TABLE IF NOT EXISTS migrations (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  migration VARCHAR(191) NOT NULL,
  batch INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `job_batches`
--
CREATE TABLE IF NOT EXISTS job_batches (
  id VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  total_jobs INT(11) NOT NULL,
  pending_jobs INT(11) NOT NULL,
  failed_jobs INT(11) NOT NULL,
  failed_job_ids LONGTEXT NOT NULL,
  options MEDIUMTEXT DEFAULT NULL,
  cancelled_at INT(11) DEFAULT NULL,
  created_at INT(11) NOT NULL,
  finished_at INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `jobs`
--
CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  queue VARCHAR(191) NOT NULL,
  payload LONGTEXT NOT NULL,
  attempts TINYINT(3) UNSIGNED NOT NULL,
  reserved_at INT(10) UNSIGNED DEFAULT NULL,
  available_at INT(10) UNSIGNED NOT NULL,
  created_at INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `jobs_queue_index` on table `jobs`
--
ALTER TABLE jobs 
  ADD INDEX jobs_queue_index(queue);

--
-- Create table `failed_jobs`
--
CREATE TABLE IF NOT EXISTS failed_jobs (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid VARCHAR(191) NOT NULL,
  `connection` TEXT NOT NULL,
  queue TEXT NOT NULL,
  payload LONGTEXT NOT NULL,
  exception LONGTEXT NOT NULL,
  failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `failed_jobs_uuid_unique` on table `failed_jobs`
--
ALTER TABLE failed_jobs 
  ADD UNIQUE INDEX failed_jobs_uuid_unique(uuid);

--
-- Create table `cache_locks`
--
CREATE TABLE IF NOT EXISTS cache_locks (
  `key` VARCHAR(191) NOT NULL,
  owner VARCHAR(191) NOT NULL,
  expiration INT(11) NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `cache`
--
CREATE TABLE IF NOT EXISTS cache (
  `key` VARCHAR(191) NOT NULL,
  value MEDIUMTEXT NOT NULL,
  expiration INT(11) NOT NULL,
  PRIMARY KEY (`key`)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;