--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2026.01.23. 7:58:08
-- Server version: 5.7.44
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS school;

CREATE DATABASE IF NOT EXISTS school
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE school;

--
-- Create table `schoolclasses`
--
CREATE TABLE IF NOT EXISTS schoolclasses (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  osztalyNev VARCHAR(10) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 25,
AVG_ROW_LENGTH = 682,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `schoolclasses_osztalynev_unique` on table `schoolclasses`
--
ALTER TABLE schoolclasses 
  ADD UNIQUE INDEX schoolclasses_osztalynev_unique(osztalyNev);

--
-- Create table `students`
--
CREATE TABLE IF NOT EXISTS students (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  diakNev VARCHAR(191) NOT NULL,
  schoolclassId BIGINT(20) UNSIGNED NOT NULL,
  neme TINYINT(1) NOT NULL DEFAULT 1,
  iranyitoszam VARCHAR(191) DEFAULT NULL,
  lakHelyseg VARCHAR(191) DEFAULT NULL,
  lakCim VARCHAR(191) DEFAULT NULL,
  szulHelyseg VARCHAR(191) DEFAULT NULL,
  szulDatum DATE DEFAULT NULL,
  igazolvanyszam VARCHAR(191) DEFAULT NULL,
  atlag DECIMAL(2, 1) DEFAULT NULL,
  osztondij DECIMAL(10, 0) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 673,
AVG_ROW_LENGTH = 195,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `students_igazolvanyszam_unique` on table `students`
--
ALTER TABLE students 
  ADD UNIQUE INDEX students_igazolvanyszam_unique(igazolvanyszam);

--
-- Create foreign key
--
ALTER TABLE students 
  ADD CONSTRAINT students_schoolclassid_foreign FOREIGN KEY (schoolclassId)
    REFERENCES schoolclasses(id);

--
-- Create table `sports`
--
CREATE TABLE IF NOT EXISTS sports (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  sportNev VARCHAR(75) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 31,
AVG_ROW_LENGTH = 528,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `sports_sportnev_unique` on table `sports`
--
ALTER TABLE sports 
  ADD UNIQUE INDEX sports_sportnev_unique(sportNev);

--
-- Create table `playingsports`
--
CREATE TABLE IF NOT EXISTS playingsports (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  studentId BIGINT(20) UNSIGNED NOT NULL,
  sportId BIGINT(20) UNSIGNED NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 675,
AVG_ROW_LENGTH = 97,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `playingsports_studentid_sportid_unique` on table `playingsports`
--
ALTER TABLE playingsports 
  ADD UNIQUE INDEX playingsports_studentid_sportid_unique(studentId, sportId);

--
-- Create foreign key
--
ALTER TABLE playingsports 
  ADD CONSTRAINT playingsports_sportid_foreign FOREIGN KEY (sportId)
    REFERENCES sports(id);

--
-- Create foreign key
--
ALTER TABLE playingsports 
  ADD CONSTRAINT playingsports_studentid_foreign FOREIGN KEY (studentId)
    REFERENCES students(id);

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  email VARCHAR(191) NOT NULL,
  role INT(11) NOT NULL DEFAULT 3,
  email_verified_at TIMESTAMP NULL DEFAULT NULL,
  password VARCHAR(191) NOT NULL,
  remember_token VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `users_email_unique` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX users_email_unique(email);

--
-- Create table `sessions`
--
CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(191) NOT NULL,
  user_id BIGINT(20) UNSIGNED DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  payload LONGTEXT NOT NULL,
  last_activity INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create index `sessions_last_activity_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_last_activity_index(last_activity);

--
-- Create index `sessions_user_id_index` on table `sessions`
--
ALTER TABLE sessions 
  ADD INDEX sessions_user_id_index(user_id);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;